// Code generated by go run ./scripts/generate-protocols; DO NOT EDIT.
export const PROTOCOLS = [
  { id: "openai-chat", label: "OpenAI Chat", async: false, requiresModelTargets: false, alwaysConfirmPaid: false, confirmPaidBatch: false },
  { id: "kimi-k3", label: "Kimi K3", async: false, requiresModelTargets: false, alwaysConfirmPaid: false, confirmPaidBatch: false },
  { id: "seedance", label: "Seedance", async: true, requiresModelTargets: false, alwaysConfirmPaid: false, confirmPaidBatch: true },
  { id: "wan-video", label: "Wan Video", async: true, requiresModelTargets: true, alwaysConfirmPaid: true, confirmPaidBatch: false },
  { id: "minimax-video", label: "MiniMax Video", async: true, requiresModelTargets: true, alwaysConfirmPaid: true, confirmPaidBatch: false },
] as const

export type ProtocolID = typeof PROTOCOLS[number]["id"]
