// Command generate-protocols publishes the Go protocol contract to TypeScript.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"

	"github.com/894x/llm-test-studio/internal/protocol"
)

func main() {
	output := flag.String("output", "apps/desktop/frontend/src/features/catalog/protocols.generated.ts", "generated TypeScript module")
	check := flag.Bool("check", false, "fail if the checked-in module is stale")
	flag.Parse()
	var source bytes.Buffer
	fmt.Fprintln(&source, "// Code generated by go run ./scripts/generate-protocols; DO NOT EDIT.")
	fmt.Fprintln(&source, "export const PROTOCOLS = [")
	for _, descriptor := range protocol.All() {
		fmt.Fprintf(&source, "  { id: %q, label: %q, async: %t, requiresModelTargets: %t, alwaysConfirmPaid: %t, confirmPaidBatch: %t },\n", descriptor.ID, descriptor.Label, descriptor.Async, descriptor.RequiresModelTargets, descriptor.AlwaysConfirmPaid, descriptor.ConfirmPaidBatch)
	}
	fmt.Fprintln(&source, "] as const\n\nexport type ProtocolID = typeof PROTOCOLS[number][\"id\"]")
	if *check {
		actual, err := os.ReadFile(*output)
		if err != nil || !bytes.Equal(bytes.ReplaceAll(actual, []byte("\r\n"), []byte("\n")), source.Bytes()) {
			fmt.Fprintln(os.Stderr, "protocol module is stale; run go run ./scripts/generate-protocols from the repository root")
			os.Exit(1)
		}
		return
	}
	if err := os.WriteFile(*output, source.Bytes(), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
